=== inesAmri56/tp1_SOA/src/cinema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/cinema" xmlns:tns="http://www.example.org/cinema" elementFormDefault="qualified">

    <complexType name="film">
    	<sequence>
    		<element name="titre" type="string"></element>
    		<element name="annee" type="string"></element>
    		<element name="realisateur" type="string"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="producteur">
    	<sequence>
    		<element name="nom" type="string"></element>
    		<element name="film" type="tns:film"></element>
    	</sequence>
    </complexType>

    <complexType name="cinema">
    	<sequence>
    		<element name="film" type="tns:film"></element>
    		<element name="producteur" type="tns:producteur"></element>
    	</sequence>
    </complexType>

    <element name="cinema" type="tns:cinema"></element>
</schema>

=== inesAmri56/tp1_SOA/src/cinema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:cinema xmlns:tns="http://www.example.org/cinema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/cinema cinema.xsd ">
  <tns:film id="" type="">
    <tns:titre>tns:titre</tns:titre>
    <tns:annee>tns:annee</tns:annee>
    <tns:realisateur>tns:realisateur</tns:realisateur>
  </tns:film>
  <tns:producteur>
    <tns:nom>tns:nom</tns:nom>
    <tns:film id="" type="">
      <tns:titre>tns:titre</tns:titre>
      <tns:annee>tns:annee</tns:annee>
      <tns:realisateur>tns:realisateur</tns:realisateur>
    </tns:film>
  </tns:producteur>
</tns:cinema>
